# This is a example for the gitlab ci.
# It will publish your app with the help of expo
# on each push in the master branch.

# IMPORTANT:
# You need to define the following environment variables
# in your gitlab interface ("Settings" -> "CI / CD" -> "Variables"):
# EXPO_CLI_USERNAME
# EXPO_CLI_PASSWORD
# or
# EXPO_TOKEN (you need at least expo-cli v4)

---
image: patwoz/expo-cli:4

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - lint
  - publish

before_script:
  - yarn install --pure-lockfile --non-interactive
  - sysctl fs.inotify.max_user_watches=524288 && sysctl -p

lint:
  stage: lint
  script:
    - yarn run lint

expo-publish:
  stage: publish
  script:
    - expo login --non-interactive -u "$EXPO_CLI_USERNAME"
    - expo publish --non-interactive
  only:
    - master
